CPPFLAGS = -g -Wall -std=c++11

%: %.cpp
	g++ $(CPPFLAGS) $^ -o $@

clean:
	rm -f *~ *.o \
		use_find \
		accum \
		equal \
		copy \
		replace \
		replace_copy \
		newcount-size \
		abs_int \
		lambda \
		inserters \
		bind2 \
		use-istream-iter \
		ostream-iter2
 