CPPFLAGS = -g -Wall -std=c++11

%: %.cpp
	g++ $(CPPFLAGS) $^ -o $@

clean:
	rm -f *~ *.o \
		factorial \
		gcd \
		eval_prefix \
		ld_list_rec_samples \
		max_recursive \
		hanoi \
		ruler \
		ruler2 \
		fibonacci1 \
		fibonacci2 \
		fibonacci3 \
		knapsack1 \
		knapsack2 \
		tree_traversal \
		nonrec_tree_traversal \
		tree_prop
