fileno: fileno_test.c
	gcc -g -Wall fileno_test.c -o fileno

newshound2: newshound2.c
	gcc -g -Wall newshound2.c -o newshound2

news_opener: news_opener.c
	gcc -g -Wall news_opener.c -o news_opener

greetings: greetings.c
	gcc -g -Wall greetings.c -o greetings

math_master: math_master.c
	gcc -g -Wall math_master.c -o math_master

clean:
	rm -f *~ *.o fileno newshound2 news_opener greetings math_master
