argument: argument.c
	gcc -g -Wall argument.c -lpthread -o argument

beer: beer.c
	gcc -g -Wall beer.c -lpthread -o beer

thread_no: thread_no.c
	gcc -g -Wall thread_no.c -lpthread -o thread_no

clean:
	rm -f *~ *.o argument beer thread_no
